image: google/cloud-sdk:slim

stages:
  - deploy

deploy_app_engine:
  stage: deploy
  script:
    - gcloud auth activate-service-account --key-file $GOOGLE_SERVICE_ACCOUNT_FILE
    - gcloud app deploy app.yaml --quiet --project $GOOGLE_PROJECT_ID

  only:
    - master
